@controller_HostAddress = http://localhost:5179

GET {{controller_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{controller_HostAddress}}/pizza/
Accept: application/json

###

GET {{controller_HostAddress}}/pizza/1
Accept: application/json

###

POST {{controller_HostAddress}}/pizza/
Content-Type: application/json

{
    "name": "Hawaii",
    "isGlutenFree": false
}

###

PUT {{controller_HostAddress}}/pizza/3
Content-Type: application/json

{
    "id": 3,
    "name": "Hawaiian",
    "isGlutenFree": false
}

###

DELETE {{controller_HostAddress}}/pizza/3

###
